#!/bin/bash

sourceTargets='\.py$|\.R$|\.java$|\.sh$|\.pl$|\.xml$|Dockerfile|Makefile|Jenkinsfile|\.toml$|\.rs$|\.rb$|\.cpp$|\.hpp$|\.H$|\.C$|\.c$|\.cc$|\.hh$|\.h$|\.ex$|\.exs$|\.erl$|\.groovy$|\.scala$|\.yaml$|\.yml$|\.j2$|\.tf$|\.R$|\.cs$|\.wdl$|\.json$|\.go$|\.nf$|\.feature$|\.js$'

if [[ "x$1" == "x" ]]
then
    find . -type f | grep -E $sourceTargets
    exit 0

elif [[ "x$2" == "x" ]]
then
  grepArgs=" "
  grepTarget=$1
else
  grepArgs=$1
  grepTarget=$2
fi

find . -not -path '*.git*' -not -path '*.tox*' -type f | grep -E $sourceTargets | grep -v ' ' | xargs grep $grepArgs "$grepTarget"
