#!/bin/bash

sourceTargets='\.py$|\.R$|\.java$|\.sh$|\.pl$|\.xml$|\.js$|\.jsx$|Dockerfile|Makefile|\.toml$|\.rs$|\.rb$|\.cpp$|\.hpp$|\.H$|\.C$|\.c$|\.h$|\.ex$|\.exs$|\.erl$|\.groovy$|\.scala$|\.yaml$|\.yml$'

if [[ "x$1" == "x" ]]
then
    find . -type f | grep -E $sourceTargets
    exit 0

elif [[ "x$2" == "x" ]]
then
  grepArgs=" "
  grepTarget=$1
else
  grepArgs=$1
  grepTarget=$2
fi

find . -type f | grep -E $sourceTargets | grep -v ' ' | xargs grep $grepArgs "$grepTarget"
