#!/usr/bin/env python

import sys
import argparse
import json

def parse_args():
    parser = argparse.ArgumentParser(description='Beautify JSON')
    parser.add_argument('jsons', nargs='+', help='One or more JSON files')
    parser.add_argument('-i', '--inplace', action='store_true', help='Update file in place')
    parser.add_argument('-I', '--indent', type=int, default=4, help='Number of spaces to indent')

    return parser.parse_args()

def main():
    args = parse_args()

    for y in args.jsons:

        with open(y, 'r') as yin:
            data = json.load(yin)

        if args.inplace:
            with open(y, 'w') as yout:
                json.dump(data, yout, indent=args.indent)
        else:
            json.dump(data, sys.stdout, indent=args.indent)
            print()

if __name__ == '__main__':
    main()
