#!/usr/bin/env python

import sys
import argparse
from ruamel.yaml import YAML

def parse_args():
    parser = argparse.ArgumentParser(description='Beautify YAML')
    parser.add_argument('yamls', nargs='+', help='One or more YAML files')
    parser.add_argument('-i', '--inplace', action='store_true', help='Update file in place')

    return parser.parse_args()

def main():
    args = parse_args()
    yaml=YAML()

    for y in args.yamls:

        with open(y, 'r') as yin:
            data = yaml.load(yin)

        if args.inplace:
            with open(y, 'w') as yout:
                yaml.dump(data, yout)
        else:
            yaml.dump(data, sys.stdout)

if __name__ == '__main__':
    main()
